version: '3'
services:

  zabbix-mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - ./data/zabbix-mysql/var/lib/mysql:/var/lib/mysql
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix 
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
  
  zabbix-server:
    restart: always
    build:  
      context: ./
      dockerfile: zabbix-server.docker
    volumes:
      - ./data/zabbix-server/var/lib/zabbix:/var/lib/zabbix
      - ./data/zabbix-server/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./data/zabbix-server/var/lib/zabbix/enc:/var/lib/zabbix/enc
      - ./data/zabbix-server/var/lib/zabbix/modules:/var/lib/zabbix/modules
      - ./data/zabbix-server/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
    ports:
      - "10050"
      - "10051"
    depends_on:
      - zabbix-mysql
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    links:
      - zabbix-mysql
 
  zabbix-frontend:
    restart: always
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.2-latest
    volumes:
      - ./data/zabbix-frontend/var/log/nginx:/var/log/nginx
    ports:
      - "8092:80"
    depends_on:
      - zabbix-mysql
    links:
      - zabbix-server
      - zabbix-mysql
      - zabbix-agent
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - PHP_TZ=Europe/Moscow
  
  zabbix-agent:
    restart: always
    image: zabbix/zabbix-agent:latest
    ports:
      - "10050"
    links:
      - zabbix-server
    environment:
      - ZBX_SERVER_HOST=zabbix-server
